---
run:
  tests: true
  skip-dirs:
    - builtin
    - examples
    - Godeps
    - locales
    - testdata
    - third_party
    - vendor
    - web
  skip-files:
    - ".*_gen\\.go$"
output:
  sort-results: true
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(source.toby3d.me)
    section-separators:
      - newLine
  goimports:
    local-prefixes: source.toby3d.me
  ireturn:
    allow:
      - error
      - stdlib
      - "(Repository|UseCase)$"
      - "sqlmock.Sqlmock"
  lll:
    tab-width: 8
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - cid # ClientID
      - ctx # context
      - db # dataBase
      - err # error
      - i # index
      - id
      - ip
      - j # alt index
      - ln # listener
      - me
      - ok
      - r # Request
      - tc # testCase
      - ts # timeStamp
      - tx # transaction
      - w # ResponseWriter
    ignore-decls:
      - "ctx context.Context"
      - "err error"
      - "i int"
      - "r *http.Request"
      - "w http.ResponseWriter"
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - source.toby3d.me
linters:
  enable-all: true
  disable:
    - godox
issues:
  exclude-rules:
    - source: "^//go:generate "
      linters:
        - lll
  fix: true
