// Code generated by qtc from "authorize.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line web/authorize.qtpl:1
package web

//line web/authorize.qtpl:1
import "source.toby3d.me/website/indieauth/internal/domain"

//line web/authorize.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/authorize.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/authorize.qtpl:3
type AuthorizePage struct {
	BaseOf
	Client              *domain.Client
	RedirectURI         *domain.URL
	Me                  *domain.Me
	CodeChallengeMethod domain.CodeChallengeMethod
	ResponseType        domain.ResponseType
	Scope               domain.Scopes
	CSRF                []byte
	CodeChallenge       string
	State               string
}

//line web/authorize.qtpl:16
func (p *AuthorizePage) StreamTitle(qw422016 *qt422016.Writer) {
//line web/authorize.qtpl:16
	qw422016.N().S(`
  `)
//line web/authorize.qtpl:17
	if p.Client.GetName() == "" {
//line web/authorize.qtpl:17
		qw422016.N().S(`
    `)
//line web/authorize.qtpl:18
		p.StreamT(qw422016, "Authorize %s", p.Client.GetName())
//line web/authorize.qtpl:18
		qw422016.N().S(`
  `)
//line web/authorize.qtpl:19
	} else {
//line web/authorize.qtpl:19
		qw422016.N().S(`
    `)
//line web/authorize.qtpl:20
		p.StreamT(qw422016, "Authorize application")
//line web/authorize.qtpl:20
		qw422016.N().S(`
  `)
//line web/authorize.qtpl:21
	}
//line web/authorize.qtpl:21
	qw422016.N().S(`
`)
//line web/authorize.qtpl:22
}

//line web/authorize.qtpl:22
func (p *AuthorizePage) WriteTitle(qq422016 qtio422016.Writer) {
//line web/authorize.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/authorize.qtpl:22
	p.StreamTitle(qw422016)
//line web/authorize.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line web/authorize.qtpl:22
}

//line web/authorize.qtpl:22
func (p *AuthorizePage) Title() string {
//line web/authorize.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line web/authorize.qtpl:22
	p.WriteTitle(qb422016)
//line web/authorize.qtpl:22
	qs422016 := string(qb422016.B)
//line web/authorize.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line web/authorize.qtpl:22
	return qs422016
//line web/authorize.qtpl:22
}

//line web/authorize.qtpl:24
func (p *AuthorizePage) StreamBody(qw422016 *qt422016.Writer) {
//line web/authorize.qtpl:24
	qw422016.N().S(`
  <header>
    `)
//line web/authorize.qtpl:26
	if p.Client.GetLogo() != nil {
//line web/authorize.qtpl:26
		qw422016.N().S(`
      <img
        alt="`)
//line web/authorize.qtpl:28
		qw422016.E().S(p.Client.GetName())
//line web/authorize.qtpl:28
		qw422016.N().S(`"
        crossorigin="anonymous"
        decoding="async"
        height="140"
        importance="high"
        loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"
        src="`)
//line web/authorize.qtpl:35
		qw422016.E().S(p.Client.GetLogo().String())
//line web/authorize.qtpl:35
		qw422016.N().S(`"
        width="140">
    `)
//line web/authorize.qtpl:37
	}
//line web/authorize.qtpl:37
	qw422016.N().S(`

    <h2>
      `)
//line web/authorize.qtpl:40
	if p.Client.GetURL() != nil {
//line web/authorize.qtpl:40
		qw422016.N().S(`
        <a href="`)
//line web/authorize.qtpl:41
		qw422016.E().S(p.Client.GetURL().String())
//line web/authorize.qtpl:41
		qw422016.N().S(`">
      `)
//line web/authorize.qtpl:42
	}
//line web/authorize.qtpl:42
	qw422016.N().S(`
      `)
//line web/authorize.qtpl:43
	if p.Client.GetName() != "" {
//line web/authorize.qtpl:43
		qw422016.N().S(`
        `)
//line web/authorize.qtpl:44
		qw422016.E().S(p.Client.GetName())
//line web/authorize.qtpl:44
		qw422016.N().S(`
      `)
//line web/authorize.qtpl:45
	} else {
//line web/authorize.qtpl:45
		qw422016.N().S(`
        `)
//line web/authorize.qtpl:46
		qw422016.E().S(p.Client.ID.String())
//line web/authorize.qtpl:46
		qw422016.N().S(`
      `)
//line web/authorize.qtpl:47
	}
//line web/authorize.qtpl:47
	qw422016.N().S(`
      `)
//line web/authorize.qtpl:48
	if p.Client.GetURL() != nil {
//line web/authorize.qtpl:48
		qw422016.N().S(`
        </a>
      `)
//line web/authorize.qtpl:50
	}
//line web/authorize.qtpl:50
	qw422016.N().S(`
    </h2>
  </header>

  <main>
    <form
      accept-charset="utf-8"
      action="/api/authorize"
      autocomplete="off"
      enctype="application/x-www-form-urlencoded"
      method="post"
      novalidate="true"
      target="_self">

      `)
//line web/authorize.qtpl:64
	if p.CSRF != nil {
//line web/authorize.qtpl:64
		qw422016.N().S(`
        <input
          type="hidden"
          name="_csrf"
          value="`)
//line web/authorize.qtpl:68
		qw422016.E().Z(p.CSRF)
//line web/authorize.qtpl:68
		qw422016.N().S(`">
      `)
//line web/authorize.qtpl:69
	}
//line web/authorize.qtpl:69
	qw422016.N().S(`

      `)
//line web/authorize.qtpl:71
	for key, val := range map[string]string{
		"client_id":     p.Client.ID.String(),
		"redirect_uri":  p.RedirectURI.String(),
		"response_type": p.ResponseType.String(),
		"state":         p.State,
	} {
//line web/authorize.qtpl:76
		qw422016.N().S(`
        <input
          type="hidden"
          name="`)
//line web/authorize.qtpl:79
		qw422016.E().S(key)
//line web/authorize.qtpl:79
		qw422016.N().S(`"
          value="`)
//line web/authorize.qtpl:80
		qw422016.E().S(val)
//line web/authorize.qtpl:80
		qw422016.N().S(`">
      `)
//line web/authorize.qtpl:81
	}
//line web/authorize.qtpl:81
	qw422016.N().S(`

      `)
//line web/authorize.qtpl:83
	if len(p.Scope) > 0 {
//line web/authorize.qtpl:83
		qw422016.N().S(`
      <fieldset>
        <legend>`)
//line web/authorize.qtpl:85
		p.StreamT(qw422016, "Choose your scopes")
//line web/authorize.qtpl:85
		qw422016.N().S(`</legend>

        `)
//line web/authorize.qtpl:87
		for _, scope := range p.Scope {
//line web/authorize.qtpl:87
			qw422016.N().S(`
          <div>
            <label>
              <input
                type="checkbox"
                name="scope[]"
                value="`)
//line web/authorize.qtpl:93
			qw422016.E().S(scope.String())
//line web/authorize.qtpl:93
			qw422016.N().S(`"
                checked>

              `)
//line web/authorize.qtpl:96
			qw422016.E().S(scope.String())
//line web/authorize.qtpl:96
			qw422016.N().S(`
            </label>
          </div>
        `)
//line web/authorize.qtpl:99
		}
//line web/authorize.qtpl:99
		qw422016.N().S(`
      </fieldset>
      `)
//line web/authorize.qtpl:101
	}
//line web/authorize.qtpl:101
	qw422016.N().S(`

      `)
//line web/authorize.qtpl:103
	if p.CodeChallenge != "" {
//line web/authorize.qtpl:103
		qw422016.N().S(`
        <input
          type="hidden"
          name="code_challenge"
          value="`)
//line web/authorize.qtpl:107
		qw422016.E().S(p.CodeChallenge)
//line web/authorize.qtpl:107
		qw422016.N().S(`">

        <input
          type="hidden"
          name="code_challenge_method"
          value="`)
//line web/authorize.qtpl:112
		qw422016.E().S(p.CodeChallengeMethod.String())
//line web/authorize.qtpl:112
		qw422016.N().S(`">
      `)
//line web/authorize.qtpl:113
	}
//line web/authorize.qtpl:113
	qw422016.N().S(`

      `)
//line web/authorize.qtpl:115
	if p.Me != nil {
//line web/authorize.qtpl:115
		qw422016.N().S(`
        <input
          type="hidden"
          name="me"
          value="`)
//line web/authorize.qtpl:119
		qw422016.E().S(p.Me.String())
//line web/authorize.qtpl:119
		qw422016.N().S(`">
      `)
//line web/authorize.qtpl:120
	}
//line web/authorize.qtpl:120
	qw422016.N().S(`

      <button
        type="submit"
        name="authorize"
        value="deny">

        `)
//line web/authorize.qtpl:127
	p.StreamT(qw422016, "Deny")
//line web/authorize.qtpl:127
	qw422016.N().S(`
      </button>

      <button
        type="submit"
        name="authorize"
        value="allow">

        `)
//line web/authorize.qtpl:135
	p.StreamT(qw422016, "Allow")
//line web/authorize.qtpl:135
	qw422016.N().S(`
      </button>
    </form>
  </main>
`)
//line web/authorize.qtpl:139
}

//line web/authorize.qtpl:139
func (p *AuthorizePage) WriteBody(qq422016 qtio422016.Writer) {
//line web/authorize.qtpl:139
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/authorize.qtpl:139
	p.StreamBody(qw422016)
//line web/authorize.qtpl:139
	qt422016.ReleaseWriter(qw422016)
//line web/authorize.qtpl:139
}

//line web/authorize.qtpl:139
func (p *AuthorizePage) Body() string {
//line web/authorize.qtpl:139
	qb422016 := qt422016.AcquireByteBuffer()
//line web/authorize.qtpl:139
	p.WriteBody(qb422016)
//line web/authorize.qtpl:139
	qs422016 := string(qb422016.B)
//line web/authorize.qtpl:139
	qt422016.ReleaseByteBuffer(qb422016)
//line web/authorize.qtpl:139
	return qs422016
//line web/authorize.qtpl:139
}
