// Code generated by qtc from "baseof.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../web/baseof.qtpl:1
package web

//line ../../web/baseof.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../web/baseof.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../web/baseof.qtpl:1
type Page interface {
//line ../../web/baseof.qtpl:1
	Lang() string
//line ../../web/baseof.qtpl:1
	StreamLang(qw422016 *qt422016.Writer)
//line ../../web/baseof.qtpl:1
	WriteLang(qq422016 qtio422016.Writer)
//line ../../web/baseof.qtpl:1
	Title() string
//line ../../web/baseof.qtpl:1
	StreamTitle(qw422016 *qt422016.Writer)
//line ../../web/baseof.qtpl:1
	WriteTitle(qq422016 qtio422016.Writer)
//line ../../web/baseof.qtpl:1
	Head() string
//line ../../web/baseof.qtpl:1
	StreamHead(qw422016 *qt422016.Writer)
//line ../../web/baseof.qtpl:1
	WriteHead(qq422016 qtio422016.Writer)
//line ../../web/baseof.qtpl:1
	Body() string
//line ../../web/baseof.qtpl:1
	StreamBody(qw422016 *qt422016.Writer)
//line ../../web/baseof.qtpl:1
	WriteBody(qq422016 qtio422016.Writer)
//line ../../web/baseof.qtpl:1
}

//line ../../web/baseof.qtpl:9
type BaseOf struct{}

//line ../../web/baseof.qtpl:12
func (p *BaseOf) StreamLang(qw422016 *qt422016.Writer) {
//line ../../web/baseof.qtpl:12
	qw422016.N().S(`en`)
//line ../../web/baseof.qtpl:12
}

//line ../../web/baseof.qtpl:12
func (p *BaseOf) WriteLang(qq422016 qtio422016.Writer) {
//line ../../web/baseof.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../web/baseof.qtpl:12
	p.StreamLang(qw422016)
//line ../../web/baseof.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line ../../web/baseof.qtpl:12
}

//line ../../web/baseof.qtpl:12
func (p *BaseOf) Lang() string {
//line ../../web/baseof.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../web/baseof.qtpl:12
	p.WriteLang(qb422016)
//line ../../web/baseof.qtpl:12
	qs422016 := string(qb422016.B)
//line ../../web/baseof.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../web/baseof.qtpl:12
	return qs422016
//line ../../web/baseof.qtpl:12
}

//line ../../web/baseof.qtpl:14
func (p *BaseOf) StreamTitle(qw422016 *qt422016.Writer) {
//line ../../web/baseof.qtpl:14
	qw422016.N().S(`Title`)
//line ../../web/baseof.qtpl:14
}

//line ../../web/baseof.qtpl:14
func (p *BaseOf) WriteTitle(qq422016 qtio422016.Writer) {
//line ../../web/baseof.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../web/baseof.qtpl:14
	p.StreamTitle(qw422016)
//line ../../web/baseof.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line ../../web/baseof.qtpl:14
}

//line ../../web/baseof.qtpl:14
func (p *BaseOf) Title() string {
//line ../../web/baseof.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../web/baseof.qtpl:14
	p.WriteTitle(qb422016)
//line ../../web/baseof.qtpl:14
	qs422016 := string(qb422016.B)
//line ../../web/baseof.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../web/baseof.qtpl:14
	return qs422016
//line ../../web/baseof.qtpl:14
}

//line ../../web/baseof.qtpl:16
func (p *BaseOf) StreamHead(qw422016 *qt422016.Writer) {
//line ../../web/baseof.qtpl:16
}

//line ../../web/baseof.qtpl:16
func (p *BaseOf) WriteHead(qq422016 qtio422016.Writer) {
//line ../../web/baseof.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../web/baseof.qtpl:16
	p.StreamHead(qw422016)
//line ../../web/baseof.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line ../../web/baseof.qtpl:16
}

//line ../../web/baseof.qtpl:16
func (p *BaseOf) Head() string {
//line ../../web/baseof.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../web/baseof.qtpl:16
	p.WriteHead(qb422016)
//line ../../web/baseof.qtpl:16
	qs422016 := string(qb422016.B)
//line ../../web/baseof.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../web/baseof.qtpl:16
	return qs422016
//line ../../web/baseof.qtpl:16
}

//line ../../web/baseof.qtpl:18
func (p *BaseOf) StreamBody(qw422016 *qt422016.Writer) {
//line ../../web/baseof.qtpl:18
}

//line ../../web/baseof.qtpl:18
func (p *BaseOf) WriteBody(qq422016 qtio422016.Writer) {
//line ../../web/baseof.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../web/baseof.qtpl:18
	p.StreamBody(qw422016)
//line ../../web/baseof.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line ../../web/baseof.qtpl:18
}

//line ../../web/baseof.qtpl:18
func (p *BaseOf) Body() string {
//line ../../web/baseof.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../web/baseof.qtpl:18
	p.WriteBody(qb422016)
//line ../../web/baseof.qtpl:18
	qs422016 := string(qb422016.B)
//line ../../web/baseof.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../web/baseof.qtpl:18
	return qs422016
//line ../../web/baseof.qtpl:18
}

//line ../../web/baseof.qtpl:20
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line ../../web/baseof.qtpl:20
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="`)
//line ../../web/baseof.qtpl:22
	p.StreamLang(qw422016)
//line ../../web/baseof.qtpl:22
	qw422016.N().S(`">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>`)
//line ../../web/baseof.qtpl:26
	p.StreamTitle(qw422016)
//line ../../web/baseof.qtpl:26
	qw422016.N().S(`</title>
    `)
//line ../../web/baseof.qtpl:27
	p.StreamHead(qw422016)
//line ../../web/baseof.qtpl:27
	qw422016.N().S(`
  </head>
  <body>
    `)
//line ../../web/baseof.qtpl:30
	p.StreamBody(qw422016)
//line ../../web/baseof.qtpl:30
	qw422016.N().S(`
  </body>
</html>
`)
//line ../../web/baseof.qtpl:33
}

//line ../../web/baseof.qtpl:33
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line ../../web/baseof.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../web/baseof.qtpl:33
	StreamPageTemplate(qw422016, p)
//line ../../web/baseof.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line ../../web/baseof.qtpl:33
}

//line ../../web/baseof.qtpl:33
func PageTemplate(p Page) string {
//line ../../web/baseof.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../web/baseof.qtpl:33
	WritePageTemplate(qb422016, p)
//line ../../web/baseof.qtpl:33
	qs422016 := string(qb422016.B)
//line ../../web/baseof.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../web/baseof.qtpl:33
	return qs422016
//line ../../web/baseof.qtpl:33
}
