// Code generated by qtc from "baseof.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line web/baseof.qtpl:1
package web

//line web/baseof.qtpl:1
import (
	"runtime/debug"

	"golang.org/x/text/language"
	"golang.org/x/text/message"

	"source.toby3d.me/toby3d/auth/internal/domain"
)

//line web/baseof.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/baseof.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/baseof.qtpl:10
type Page interface {
//line web/baseof.qtpl:10
	Body() string
//line web/baseof.qtpl:10
	StreamBody(qw422016 *qt422016.Writer)
//line web/baseof.qtpl:10
	WriteBody(qq422016 qtio422016.Writer)
//line web/baseof.qtpl:10
	Head() string
//line web/baseof.qtpl:10
	StreamHead(qw422016 *qt422016.Writer)
//line web/baseof.qtpl:10
	WriteHead(qq422016 qtio422016.Writer)
//line web/baseof.qtpl:10
	Lang() string
//line web/baseof.qtpl:10
	StreamLang(qw422016 *qt422016.Writer)
//line web/baseof.qtpl:10
	WriteLang(qq422016 qtio422016.Writer)
//line web/baseof.qtpl:10
	Title() string
//line web/baseof.qtpl:10
	StreamTitle(qw422016 *qt422016.Writer)
//line web/baseof.qtpl:10
	WriteTitle(qq422016 qtio422016.Writer)
//line web/baseof.qtpl:10
	T(format string, args ...interface{}) string
//line web/baseof.qtpl:10
	StreamT(qw422016 *qt422016.Writer, format string, args ...interface{})
//line web/baseof.qtpl:10
	WriteT(qq422016 qtio422016.Writer, format string, args ...interface{})
//line web/baseof.qtpl:10
}

//line web/baseof.qtpl:18
type BaseOf struct {
	Config   *domain.Config
	Language language.Tag
	Printer  *message.Printer
}

//line web/baseof.qtpl:25
func (p *BaseOf) StreamLang(qw422016 *qt422016.Writer) {
//line web/baseof.qtpl:26
	if p.Language != language.Und {
//line web/baseof.qtpl:27
		qw422016.E().S(p.Language.String())
//line web/baseof.qtpl:28
	} else {
//line web/baseof.qtpl:28
		qw422016.N().S(`en`)
//line web/baseof.qtpl:30
	}
//line web/baseof.qtpl:31
}

//line web/baseof.qtpl:31
func (p *BaseOf) WriteLang(qq422016 qtio422016.Writer) {
//line web/baseof.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/baseof.qtpl:31
	p.StreamLang(qw422016)
//line web/baseof.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line web/baseof.qtpl:31
}

//line web/baseof.qtpl:31
func (p *BaseOf) Lang() string {
//line web/baseof.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line web/baseof.qtpl:31
	p.WriteLang(qb422016)
//line web/baseof.qtpl:31
	qs422016 := string(qb422016.B)
//line web/baseof.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line web/baseof.qtpl:31
	return qs422016
//line web/baseof.qtpl:31
}

//line web/baseof.qtpl:35
func (p *BaseOf) StreamTitle(qw422016 *qt422016.Writer) {
//line web/baseof.qtpl:35
	qw422016.N().S(` `)
//line web/baseof.qtpl:36
	qw422016.E().S(p.Config.Name)
//line web/baseof.qtpl:36
	qw422016.N().S(` `)
//line web/baseof.qtpl:37
}

//line web/baseof.qtpl:37
func (p *BaseOf) WriteTitle(qq422016 qtio422016.Writer) {
//line web/baseof.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/baseof.qtpl:37
	p.StreamTitle(qw422016)
//line web/baseof.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line web/baseof.qtpl:37
}

//line web/baseof.qtpl:37
func (p *BaseOf) Title() string {
//line web/baseof.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line web/baseof.qtpl:37
	p.WriteTitle(qb422016)
//line web/baseof.qtpl:37
	qs422016 := string(qb422016.B)
//line web/baseof.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line web/baseof.qtpl:37
	return qs422016
//line web/baseof.qtpl:37
}

//line web/baseof.qtpl:39
func (p *BaseOf) StreamHead(qw422016 *qt422016.Writer) {
//line web/baseof.qtpl:39
	qw422016.N().S(` `)
//line web/baseof.qtpl:40
	qw422016.N().S(` <link rel="icon" href="`)
//line web/baseof.qtpl:42
	qw422016.E().S(p.Config.Server.StaticURLPrefix)
//line web/baseof.qtpl:42
	qw422016.N().S(`/favicon.ico" sizes="any"> <link rel="icon" href="`)
//line web/baseof.qtpl:46
	qw422016.E().S(p.Config.Server.StaticURLPrefix)
//line web/baseof.qtpl:46
	qw422016.N().S(`/icon.svg" type="image/svg+xml"> <link rel="apple-touch-icon" href="`)
//line web/baseof.qtpl:50
	qw422016.E().S(p.Config.Server.StaticURLPrefix)
//line web/baseof.qtpl:50
	qw422016.N().S(`/apple-touch-icon.png"> <link rel="manifest" href="`)
//line web/baseof.qtpl:53
	qw422016.E().S(p.Config.Server.StaticURLPrefix)
//line web/baseof.qtpl:53
	qw422016.N().S(`/manifest.webmanifest"> `)
//line web/baseof.qtpl:54
}

//line web/baseof.qtpl:54
func (p *BaseOf) WriteHead(qq422016 qtio422016.Writer) {
//line web/baseof.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/baseof.qtpl:54
	p.StreamHead(qw422016)
//line web/baseof.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line web/baseof.qtpl:54
}

//line web/baseof.qtpl:54
func (p *BaseOf) Head() string {
//line web/baseof.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line web/baseof.qtpl:54
	p.WriteHead(qb422016)
//line web/baseof.qtpl:54
	qs422016 := string(qb422016.B)
//line web/baseof.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line web/baseof.qtpl:54
	return qs422016
//line web/baseof.qtpl:54
}

//line web/baseof.qtpl:56
func (p *BaseOf) StreamBody(qw422016 *qt422016.Writer) {
//line web/baseof.qtpl:56
}

//line web/baseof.qtpl:56
func (p *BaseOf) WriteBody(qq422016 qtio422016.Writer) {
//line web/baseof.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/baseof.qtpl:56
	p.StreamBody(qw422016)
//line web/baseof.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line web/baseof.qtpl:56
}

//line web/baseof.qtpl:56
func (p *BaseOf) Body() string {
//line web/baseof.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line web/baseof.qtpl:56
	p.WriteBody(qb422016)
//line web/baseof.qtpl:56
	qs422016 := string(qb422016.B)
//line web/baseof.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line web/baseof.qtpl:56
	return qs422016
//line web/baseof.qtpl:56
}

//line web/baseof.qtpl:58
func StreamTemplate(qw422016 *qt422016.Writer, p Page) {
//line web/baseof.qtpl:58
	qw422016.N().S(` <!DOCTYPE html> <html class="page" lang="`)
//line web/baseof.qtpl:61
	p.StreamLang(qw422016)
//line web/baseof.qtpl:61
	qw422016.N().S(`"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> `)
//line web/baseof.qtpl:67
	p.StreamHead(qw422016)
//line web/baseof.qtpl:67
	qw422016.N().S(` <title>`)
//line web/baseof.qtpl:69
	p.StreamTitle(qw422016)
//line web/baseof.qtpl:69
	qw422016.N().S(`</title> </head> <body class="page__body body"> `)
//line web/baseof.qtpl:72
	p.StreamBody(qw422016)
//line web/baseof.qtpl:72
	qw422016.N().S(` `)
//line web/baseof.qtpl:75
	var path, vcsRevision string

	if bi, ok := debug.ReadBuildInfo(); ok {
		path = bi.Path

		for i := range bi.Settings {
			if bi.Settings[i].Key != "vcs.revision" {
				continue
			}

			vcsRevision = bi.Settings[i].Value
		}
	}

//line web/baseof.qtpl:88
	qw422016.N().S(` `)
//line web/baseof.qtpl:90
	if vcsRevision != "" {
//line web/baseof.qtpl:90
		qw422016.N().S(` <footer> <small> `)
//line web/baseof.qtpl:93
		p.StreamT(qw422016, "version")
//line web/baseof.qtpl:93
		qw422016.N().S(` <a href="https://`)
//line web/baseof.qtpl:94
		qw422016.E().S(path)
//line web/baseof.qtpl:94
		qw422016.N().S(`/commit/`)
//line web/baseof.qtpl:94
		qw422016.E().S(vcsRevision)
//line web/baseof.qtpl:94
		qw422016.N().S(`" target="_blank"> `)
//line web/baseof.qtpl:95
		qw422016.E().S(vcsRevision[:7])
//line web/baseof.qtpl:95
		qw422016.N().S(`</a> </small> </footer> `)
//line web/baseof.qtpl:99
	}
//line web/baseof.qtpl:99
	qw422016.N().S(` </body> </html> `)
//line web/baseof.qtpl:102
}

//line web/baseof.qtpl:102
func WriteTemplate(qq422016 qtio422016.Writer, p Page) {
//line web/baseof.qtpl:102
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/baseof.qtpl:102
	StreamTemplate(qw422016, p)
//line web/baseof.qtpl:102
	qt422016.ReleaseWriter(qw422016)
//line web/baseof.qtpl:102
}

//line web/baseof.qtpl:102
func Template(p Page) string {
//line web/baseof.qtpl:102
	qb422016 := qt422016.AcquireByteBuffer()
//line web/baseof.qtpl:102
	WriteTemplate(qb422016, p)
//line web/baseof.qtpl:102
	qs422016 := string(qb422016.B)
//line web/baseof.qtpl:102
	qt422016.ReleaseByteBuffer(qb422016)
//line web/baseof.qtpl:102
	return qs422016
//line web/baseof.qtpl:102
}

//line web/baseof.qtpl:104
func (p *BaseOf) StreamT(qw422016 *qt422016.Writer, format string, args ...interface{}) {
//line web/baseof.qtpl:104
	qw422016.N().S(` `)
//line web/baseof.qtpl:105
	qw422016.E().S(p.Printer.Sprintf(format, args...))
//line web/baseof.qtpl:105
	qw422016.N().S(` `)
//line web/baseof.qtpl:106
}

//line web/baseof.qtpl:106
func (p *BaseOf) WriteT(qq422016 qtio422016.Writer, format string, args ...interface{}) {
//line web/baseof.qtpl:106
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/baseof.qtpl:106
	p.StreamT(qw422016, format, args...)
//line web/baseof.qtpl:106
	qt422016.ReleaseWriter(qw422016)
//line web/baseof.qtpl:106
}

//line web/baseof.qtpl:106
func (p *BaseOf) T(format string, args ...interface{}) string {
//line web/baseof.qtpl:106
	qb422016 := qt422016.AcquireByteBuffer()
//line web/baseof.qtpl:106
	p.WriteT(qb422016, format, args...)
//line web/baseof.qtpl:106
	qs422016 := string(qb422016.B)
//line web/baseof.qtpl:106
	qt422016.ReleaseByteBuffer(qb422016)
//line web/baseof.qtpl:106
	return qs422016
//line web/baseof.qtpl:106
}
